name: CD Pipeline
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your.server.com >> ~/.ssh/known_hosts
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - name: Deploy application
        run: |
          ssh user@your.server.com << 'EOF'
            cd fastapi-book-project
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF